### ISSUE TITLE
E: Unable to locate package hhvm

### ISSUE THREAD

**Issue by BenjaminX** [jlumbroso/free-disk-space#1]
![SCR-20221118-vm3](https://user-images.githubusercontent.com/612858/202731939-1dc72f88-f0e2-4026-8d6e-1e0e2f9358e6.png)

**Comment by BenjaminX** [comment]
[2_Free Disk Space (Ubuntu).txt](https://github.com/jlumbroso/free-disk-space/files/10042757/2_Free.Disk.Space.Ubuntu.txt)

**Comment by gruve-p** [comment]
Getting this also:
https://github.com/Groestlcoin/electrum-grs/actions/runs/3524233991/jobs/5915452327

**Comment by gruve-p** [comment]
@jlumbroso Is this repo still maintained?

**Comment by jlumbroso** [comment]
Thanks @BenjaminX and @gruve-p!

**Comment by jlumbroso** [comment]
Sorry @JacopKane, it is now:
https://github.com/jlumbroso/free-disk-space/releases/tag/v1.2.0

**Comment by JacopKane** [comment]
> Sorry @JacopKane, it is now: https://github.com/jlumbroso/free-disk-space/releases/tag/v1.2.0

thank you
