### ISSUE TITLE
google-cloud-sdk renamed to google-cloud-cli

### ISSUE THREAD

**Issue by sensedata1** [jlumbroso/free-disk-space#17]
Looks like gh actions hosted runners are now installing the latest renamed `google-cloud-cli` package so the action is failing when it tries to remove the deprecated `google-cloud-sdk` package
https://github.com/actions/runner-images/pull/8335
```
E: Unable to locate package google-cloud-sdk
Error: Process completed with exit code 100.
```

**Comment by Jonatha-Varjao** [comment]
Facing the same issue, just put
```
large-packages: false
```
in the options, and it worked for my case

**Comment by sensedata1** [comment]
> Facing the same issue, just put
> 
> ```
> large-packages: false
> ```
> 
> in the options, and it worked for my case

Indeed, but it would be nice not to have to throw the baby out with the bathwater. 😉

**Comment by andreped** [comment]
Made a PR: https://github.com/jlumbroso/free-disk-space/pull/18

**Comment by bhavaniravi** [comment]
Thanks for raising this and making a PR. Added this to my CI yesterday. Everything was working fine and today it broke

**Comment by jlumbroso** [comment]
@wind57 Thanks for the manual workaround! 🙏🏻

@andreped Thanks for the PR. 🥳

@briedel @v1v @bhavaniravi @sensedata1 @Jonatha-Varjao @KurtAhn @tokatoka @kenjis @sp98 Sorry for the disruption. Please let me know if the latest release `v1.3.0` addresses all your concerns. Thank you!
