### ISSUE TITLE
`404  Not Found` while removing packages

### ISSUE THREAD

**Issue by AurevoirXavier** [jlumbroso/free-disk-space#9]
```
Reading package lists...
Building dependency tree...
Reading state information...
Package 'dotnet-nightly' is not installed, so not removed
Package 'dotnet-targeting-pack-3.1' is not installed, so not removed
Package 'dotnet-host-7.0' is not installed, so not removed
Package 'dotnet-sdk-6.0-source-built-artifacts' is not installed, so not removed
Package 'dotnet-sdk-7.0-source-built-artifacts' is not installed, so not removed
Package 'dotnet-templates-6.0' is not installed, so not removed
Package 'dotnet-templates-7.0' is not installed, so not removed
Package 'dotnet-apphost-pack-3.1' is not installed, so not removed
Package 'dotnet-runtime-3.1' is not installed, so not removed
Package 'dotnet-sdk-3.1' is not installed, so not removed
Package 'dotnet-hostfxr-3.1' is not installed, so not removed
Package 'dotnet-runtime-deps-3.1' is not installed, so not removed
The following additional packages will be installed:
  aspnetcore-targeting-pack-6.0 aspnetcore-targeting-pack-7.0
The following packages will be REMOVED:
  aspnetcore-runtime-6.0 aspnetcore-runtime-7.0 dotnet-apphost-pack-6.0
  dotnet-apphost-pack-7.0 dotnet-host dotnet-hostfxr-6.0 dotnet-hostfxr-7.0
  dotnet-runtime-6.0 dotnet-runtime-7.0 dotnet-runtime-deps-6.0
  dotnet-runtime-deps-7.0 dotnet-sdk-6.0 dotnet-sdk-7.0
  dotnet-targeting-pack-6.0 dotnet-targeting-pack-7.0
The following packages will be upgraded:
  aspnetcore-targeting-pack-6.0 aspnetcore-targeting-pack-7.0
2 upgraded, 0 newly installed, 15 to remove and 15 not upgraded.
Need to get 3042 kB of archives.
After this operation, 990 MB disk space will be freed.
Ign:1 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-6.0 amd64 6.0.119-0ubuntu1~22.04.1
Ign:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-7.0 amd64 7.0.108-0ubuntu1~22.04.1
Err:1 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-6.0 amd64 6.0.119-0ubuntu1~22.04.1
  404  Not Found [IP: 40.119.46.219 80]
Err:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-7.0 amd64 7.0.108-0ubuntu1~22.04.1
  404  Not Found [IP: 40.119.46.219 80]
E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/universe/d/dotnet6/aspnetcore-targeting-pack-6.0_6.0.119-0ubuntu1%7e22.04.1_amd64.deb](http://azure.archive.ubuntu.com/ubuntu/pool/universe/d/dotnet6/aspnetcore-targeting-pack-6.0_6.0.119-0ubuntu1~22.04.1_amd64.deb)  404  Not Found [IP: 40.119.46.219 80]
E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/universe/d/dotnet7/aspnetcore-targeting-pack-7.0_7.0.108-0ubuntu1%7e22.04.1_amd64.deb](http://azure.archive.ubuntu.com/ubuntu/pool/universe/d/dotnet7/aspnetcore-targeting-pack-7.0_7.0.108-0ubuntu1~22.04.1_amd64.deb)  404  Not Found [IP: 40.119.46.219 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by buroa** [comment]
Seeing this too.

**Comment by yinweisu** [comment]
Seeing same error here too. When do we expect the fix being merged in?

**Comment by WolvenBard** [comment]
I am starting to see this error now too

**Comment by abvaidya** [comment]
Seeing this error too. Request to merge the fix.

**Comment by zaikunzhang** [comment]
This happens on my side starting from yesterday.

**Comment by zaikunzhang** [comment]
Similar problems come back starting 14 Sept 2023:
 
`
Reading package lists...
Building dependency tree...
Reading state information...
Package 'dotnet-nightly' is not installed, so not removed
Package 'dotnet-targeting-pack-3.1' is not installed, so not removed
Package 'dotnet-host-7.0' is not installed, so not removed
Package 'dotnet-sdk-6.0-source-built-artifacts' is not installed, so not removed
Package 'dotnet-sdk-7.0-source-built-artifacts' is not installed, so not removed
Package 'dotnet-templates-6.0' is not installed, so not removed
Package 'dotnet-templates-7.0' is not installed, so not removed
Package 'dotnet-apphost-pack-3.1' is not installed, so not removed
Package 'dotnet-runtime-3.1' is not installed, so not removed
Package 'dotnet-sdk-3.1' is not installed, so not removed
Package 'dotnet-hostfxr-3.1' is not installed, so not removed
Package 'dotnet-runtime-deps-3.1' is not installed, so not removed
The following additional packages will be installed:
  aspnetcore-targeting-pack-6.0 aspnetcore-targeting-pack-7.0
The following packages will be REMOVED:
  aspnetcore-runtime-6.0 aspnetcore-runtime-7.0 dotnet-apphost-pack-6.0
  dotnet-apphost-pack-7.0 dotnet-host dotnet-hostfxr-6.0 dotnet-hostfxr-7.0
  dotnet-runtime-6.0 dotnet-runtime-7.0 dotnet-runtime-deps-6.0
  dotnet-runtime-deps-7.0 dotnet-sdk-6.0 dotnet-sdk-7.0
  dotnet-targeting-pack-6.0 dotnet-targeting-pack-7.0
The following packages will be upgraded:
  aspnetcore-targeting-pack-6.0 aspnetcore-targeting-pack-7.0
2 upgraded, 0 newly installed, 15 to remove and 15 not upgraded.
Need to get 3045 kB of archives.
After this operation, 1029 MB disk space will be freed.
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Ign:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-6.0 amd64 6.0.121-0ubuntu1~22.04.1
Ign:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-7.0 amd64 7.0.110-0ubuntu1~22.04.1
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-6.0 amd64 6.0.121-0ubuntu1~22.04.1
Ign:2 http://security.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-6.0 amd64 6.0.121-0ubuntu1~22.04.1
Err:2 mirror+file:/etc/apt/apt-mirrors.txt jammy-updates/universe amd64 aspnetcore-targeting-pack-6.0 amd64 6.0.121-0ubuntu1~22.04.1
  404  Not Found [IP: 52.147.219.192 80]
Ign:3 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-7.0 amd64 7.0.110-0ubuntu1~22.04.1
Ign:3 http://security.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-7.0 amd64 7.0.110-0ubuntu1~22.04.1
Err:3 mirror+file:/etc/apt/apt-mirrors.txt jammy-updates/universe amd64 aspnetcore-targeting-pack-7.0 amd64 7.0.110-0ubuntu1~22.04.1
  404  Not Found [IP: 52.147.219.192 80]
E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/universe/d/dotnet6/aspnetcore-targeting-pack-6.0_6.0.121-0ubuntu1%7e22.04.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/universe/d/dotnet7/aspnetcore-targeting-pack-7.0_7.0.110-0ubuntu1%7e22.04.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
0s
`

**Comment by sarab5000** [comment]
@zaikunzhang   Having the same exact error

**Comment by jlumbroso** [comment]
@enoriega @myedibleenso @sarab5000 @zaikunzhang @edcdavid @hirnidrin @Leouarz @zkrige @buroa @yinweisu and other let me know if you still have the issue in `v1.3.0` now that we have merged @AurevoirXavier's and @hirnidrin fixes.
